<!-- //== Copyright (C) 2026, YouTube Contributors and dmitriykotik. ==  -->
<!-- // Released under the MIT License.                                  -->
<!-- //                                                                  -->
<!-- // This file is part of DiscordAlyona.                              -->
<!-- // This software is provided "AS IS", without warranty of any kind, -->
<!-- // express or implied, including but not limited to warranties      -->
<!-- // of merchantability, fitness for a particular purpose and         -->
<!-- // noninfringement.                                                 -->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Native\libdave.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Native\libsodium.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Native\opus.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
